/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuoteRequest = IDL.Record({
  'name' : IDL.Text,
  'orderType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getQuoteRequest' : IDL.Func([IDL.Nat], [QuoteRequest], ['query']),
  'submitQuoteRequest' : IDL.Func([QuoteRequest], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuoteRequest = IDL.Record({
    'name' : IDL.Text,
    'orderType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'getQuoteRequest' : IDL.Func([IDL.Nat], [QuoteRequest], ['query']),
    'submitQuoteRequest' : IDL.Func([QuoteRequest], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };